boost_words = set([
    'amazing',
    'bao đẹp',
    'bung chỉ',
    'bình thường',
    'bẩn',
    'bị chật',
    'bị lỗi',
    'bị méo',
    'bị nhăn',
    'bỏ mẹ',
    'bực',
    'chán',
    'chơi khăm',
    'chưa trả lời',
    'chưa đúng',
    'chả muốn nói',
    'chất lượng kém',
    'chất lượng sản phẩm kém',
    'chất lượng sản phẩm tốt',
    'chất lượng tốt',
    'chất vải',
    'chất xấu',
    'chật',
    'chỉ thừa',
    'cute',
    'cái nịt',
    'cân nhắc',
    'có vấn đề',
    'cũng ok',
    'cũng tạm',
    'cũng tốt',
    'cũng được',
    'cũng đẹp',
    'cũng ổn',
    'cơ bản',
    'cẩn thận',
    'cực thích',
    'cực đẹp',
    'cực ưng',
    'dơ',
    'dễ thương',
    'dỏm',
    'ghét',
    'giao chậm',
    'giao hàng chậm',
    'giao hàng hơi lâu',
    'giao hàng lâu',
    'giao hàng nhanh',
    'giao hàng sai',
    'giao hàng thiếu',
    'giao hơi lâu',
    'giao lâu',
    'giao màu',
    'giao màu sai',
    'giao nhanh',
    'giao sai',
    'giao sai hàng',
    'giao sai màu',
    'giao thiếu',
    'giao đúng',
    'giao đủ',
    'giá mắc',
    'giá rẻ',
    'giá tốt',
    'giá đắt',
    'giống hình',
    'giới thiệu',
    'good job',
    'gãy',
    'gớm',
    'gửi lại',
    'gửi sai',
    'hoàn sản phẩm',
    'hàng dởm',
    'hàng đẹp',
    'hàng ổn',
    'hơi khác',
    'hơi lâu',
    'hơi mỏng',
    'hơi nhỏ',
    'hơi rộng',
    'hơi trễ',
    'hợp túi tiền',
    'khuyến cáo',
    'khá mắc',
    'khá to',
    'khá tốt',
    'khá vừa',
    'khá đẹp',
    'khá ổn',
    'khác kiểu',
    'khác màu',
    'khác size',
    'khó chịu',
    'không bao giờ',
    'không che',
    'không cho đổi',
    'không chắc chắn',
    'không cách nhiệt',
    'không có giao',
    'không có gì',
    'không giao',
    'không giống',
    'không giống hình',
    'không giống ảnh',
    'không hỗ trợ',
    'không như',
    'không như hình',
    'không nhận được',
    'không nên',
    'không phù hợp',
    'không phải',
    'không sử dụng được',
    'không thèm rep',
    'không thích',
    'không vừa',
    'không đóng được',
    'không đúng',
    'không được',
    'không đẹp,không được đẹp',
    'không ưng',
    'kinh dị',
    'kém chất lượng',
    'làm ăn',
    'lâu',
    'lịch sự',
    'lộ',
    'lừa gạt',
    'lừa đảo',
    'mua nha',
    'màu bạc',
    'màu hơi bạc',
    'màu không giống',
    'mất đẹp',
    'mặc nóng',
    'mặc vừa',
    'mỏng quá',
    'mồ hôi',
    'nghĩ kĩ',
    'ngu dốt',
    'như bùi',
    'như cứt',
    'như hình',
    'như lồn',
    'nhạt',
    'nhầm kiểu',
    'nhầm màu',
    'nhầm size',
    'nhận hàng',
    'nên mua',
    'phát chán',
    'phát gớm',
    'phí tiền',
    'phù hợp',
    'quay lại',
    'quá kém',
    'quá lâu',
    'quá nhỏ',
    'quá trễ',
    'quá đẹp',
    'quần đẹp',
    'rác',
    'rách',
    'rất kinh',
    'rất kém',
    'rất lâu',
    'rất đáng',
    'rất đẹp',
    'rắc rối',
    'sai lầm',
    'sai màu',
    'sai size',
    'sale,mua sale',
    'ship chậm',
    'ship hàng',
    'ship lâu',
    'shipper',
    'sida',
    'sản phẩm kém',
    'sản phẩm lỗi',
    'sản phẩm tốt',
    'sản phẩm đẹp',
    'sống nhăn',
    'sờn',
    'thun đẹp',
    'thân thiện',
    'thì đẹp',
    'thất vọng',
    'thấy chán',
    'thấy cưng',
    'thấy gớm',
    'thấy xấu',
    'thịt chó',
    'tiền nào của nấy',
    'tiền nào của đó',
    'trả',
    'trầy xước',
    'trễ',
    'trời ơi',
    'tuyệt vời',
    'tàm tạm',
    'tạch',
    'tạm chấp nhận',
    'tạm được',
    'tạm ổn',
    'tệ',
    'tức',
    'từ chối trả lại',
    'vải mỏng',
    'vải nóng',
    'vải xấu',
    'vải đẹp',
    'vừa vặn',
    'xinh lắm',
    'xinh xắn',
    'xinh xỉu',
    'xu cà na',
    'xấu hẳn',
    'xịn xò',
    'zip,túi zip',
    'áo đẹp',
    'đáng mua',
    'đáng tiền',
    'chắc chắn',
    'đúng giờ',
    'đường chỉ',
    'đường may',
    'đặt hàng',
    'đẹp cực',
    'đẹp lắm',
    'đẹp lắm luôn',
    'đẹp quá',
    'đổ lông',
    'đụ má',
    'đụ mẹ',
    'ưng ý',
    'ối trời ơi',
    'ủng hộ',
    "quá ok",
    "ưng quá",
    "khá xinh",
    "ngoài sức mong đợi",
    "giao hàng quá chậm",
    "thời gian giao hàng dài",
    "không nên mua",
    "hơn cả mong đợi",
    "rất hài lòng",
    "rất đẹp",
    "cũng đẹp",
    "quá đẹp",
    "chất lượng quá tuyệt vời",
    "chất lượng quá ok"
])